### ISSUE TITLE
Readme mentions AppleWin NTSC but not AppleWin

### ISSUE THREAD

**Issue by Michaelangel007** [badvision/lawless-legends#20]
The readme probably should add a link to the official AppleWin emulator as Sheldon's NTSC will eventually be obsolete with the upcoming v1.26.
- [AppleWin](https://github.com/AppleWin/AppleWin/)

**Comment by badvision** [comment]
Any word when 1.26 will be released?

**Comment by Michaelangel007** [comment]
Nothing finalized yet ... we're still working on it. :-/ Feel free to ping Tom next week.

That reminds me we need to publicly get another beta out ... :-)
