### ISSUE TITLE
//c disk access fails

### ISSUE THREAD

**Issue by dschmenk** [badvision/lawless-legends#28]
Using a ROM 3 or ROM 255 Apple //c: Once LL is loaded and tries to start a new game, the drive light flickers briefly and asks for disk 1. If a second drive is added, it will be searched but will still ask for disk 1, even if it is in drive2. The same floppies work fine with an enhanced //e.

**Comment by martinhaye** [comment]
I believe the problem is down in ProRWTS' disk detection logic. I've developed a temporary fix if you're in a hurry, or I imagine he'll have a permanent fix in a few days.

**Comment by dschmenk** [comment]
If you have built floppy images with the fix in, I can try it quickly. Otherwise I can wait.

**Comment by martinhaye** [comment]
Sure, here's a folder of disks to try. Thank you! https://www.dropbox.com/sh/s767qw3sin9zric/AAAGQ09N9hHaUFg7zi1BD2OUa?dl=0

**Comment by dschmenk** [comment]
Thanks! that got us going!
