### ISSUE TITLE
can't run from a HDD subdirectory

### ISSUE THREAD

**Issue by peterferrie** [badvision/lawless-legends#38]
The call to ProRWTS init function happens after ProDOS is overwritten by the copy of ROM to LC RAM.
ProRWTS needs to call a ProDOS function to determine the current prefix, which fails if LC RAM was written first.
The fix is to call init before making the ROM to LC RAM copy.

**Comment by martinhaye** [comment]
Fixed in our latest round of ProRWTS upgrades. Tested and working from a subdirectory.
